### ISSUE TITLE
Request for improvements

### ISSUE THREAD

**Issue by pvnsero** [Charles1403/store#1]
Hi Charles, thanks for taking the time to do this. We found few issues with your submission, appreciate if you can address them
- The build instructions in README is not sufficient, there need to be more info building client and providing config to the server.
- The main page needs to be served from the server `GET /` route.

**Comment by Charles1403** [comment]
Okay, I'll get right to it.

**Comment by Charles1403** [comment]
Hello,

This is the GitHub link to the updated Test Task
https://github.com/Charles1403/Take-home.

It is hosted at take-home-lac.vercel.app.

Regards,
Charles

**Comment by pvnsero** [comment]
Thank you

**Comment by Charles1403** [comment]
Hello,

Still no feedback?

Regards,
Charles
